create database warrior
use warrior
create table batman ( ID INT PRIMARY KEY, NAME VARCHAR(33),AGE INT,CITY VARCHAR(55))
INSERT INTO BATMAN VALUES (1,'TIA',25,'DELHI')
INSERT INTO BATMAN VALUES (2,'TIA',25,'DELHI')
INSERT INTO BATMAN VALUES (3,'TIA',25,'DELHI')
INSERT INTO BATMAN VALUES (4,'TIA',25,'DELHI')
INSERT INTO BATMAN VALUES (5,'TIA',25,'DELHI')
INSERT INTO BATMAN VALUES (6,'TIA',25,'DELHI')
INSERT INTO BATMAN VALUES (7,'TIA',25,'DELHI')
UPDATE BATMAN SET NAME='PRAJU',AGE=28,CITY='PUNE'
UPDATE BATMAN SET NAME='HENA',AGE=29,CITY='DELHI' WHERE ID=2
UPDATE BATMAN SET NAME='TIYA',AGE=22,CITY='MUMBAI' WHERE ID=3
UPDATE BATMAN SET NAME='NIKI',AGE=30,CITY='DELHI' WHERE ID=4
UPDATE BATMAN SET NAME='PIHU',AGE=28,CITY='MUMBAI' WHERE ID=5
UPDATE BATMAN SET NAME='DIYA',AGE=40,CITY='KOL' WHERE ID=6
UPDATE BATMAN SET NAME='RAJU',AGE=48,CITY='CHENNAI' WHERE ID=7
ALTER TABLE BATMAN ADD SUB VARCHAR(60)
UPDATE BATMAN SET SUB='MATHS'WHERE ID=7
UPDATE BATMAN SET SUB='SC'WHERE ID=6
UPDATE BATMAN SET SUB='BE'WHERE ID=5
UPDATE BATMAN SET SUB='BCA'WHERE ID=4
UPDATE BATMAN SET SUB='MCA'WHERE ID=3
UPDATE BATMAN SET SUB='GK'WHERE ID=2
UPDATE BATMAN SET SUB='ENG'WHERE ID=1

CREATE TABLE SPIDERMANN(ID INT PRIMARY KEY,MARKS INT,SALARY INT)
INSERT INTO SPIDERMANN VALUES (1,233,25000)
INSERT INTO SPIDERMANN VALUES (2,250,5000)
INSERT INTO SPIDERMANN VALUES (3,230,20000)
INSERT INTO SPIDERMANN VALUES (4,220,40000)
INSERT INTO SPIDERMANN VALUES (5,215,30000)
--
SELECT * FROM SPIDERMANN WHERE SALARY =30000 
SELECT MAX( MARKS) FROM SPIDERMANN
SELECT MIN( MARKS) FROM SPIDERMANN
SELECT COUNT(ID)  FROM SPIDERMANN 
SELECT SUM(ID) FROM SPIDERMANN
SELECT AVG(MARKS) FROM SPIDERMANN
SELECT MAX( MARKS) AS MARKS FROM SPIDERMANN
SELECT AVG(MARKS)FROM SPIDERMANN
SELECT MAX( MARKS) AS MARKS FROM SPIDERMANN
SELECT AVG( SALARY) AS MARKS FROM SPIDERMANN
SELECT MIN(SALARY) FROM SPIDERMANN
SELECT * FROM BATMAN WHERE NAME LIKE '%P'
SELECT * FROM BATMAN WHERE NAME LIKE 'P%'
SELECT * FROM BATMAN WHERE NAME LIKE '%A%'
SELECT * FROM BATMAN WHERE NAME LIKE '%N%'
SELECT * FROM BATMAN WHERE id between 2 and 5
SELECT * FROM batman WHERE name in ('tiya','niki')
SELECT * FROM SPIDERMANN WHERE marks between 230 and  250
------ joins
select batman.id,name from batman inner join SPIDERMANN on batman.id=SPIDERMANN.id
select batman.id,name from batman right outer join SPIDERMANN on batman.id=SPIDERMANN.id
select SPIDERMANN.id,name from batman left outer join SPIDERMANN on batman.id=SPIDERMANN.id
select batman.id name,marks,CITY from batman full outer join SPIDERMANN on batman.id=SPIDERMANN.id
select SPIDERMANN.id,MARKS from SPIDERMANN left outer join batman on batman.id=SPIDERMANN.id

SELECT * FROM BATMAN WHERE id >2 
SELECT * FROM BATMAN WHERE id <3
SELECT * FROM BATMAN WHERE id =2
SELECT * FROM BATMAN WHERE id >=2 
SELECT * FROM BATMAN WHERE id <=3
SELECT * FROM BATMAN WHERE id <>3
select top 2 * from SPIDERMANN
select top 2 * from batman
update SPIDERMANN set marks=230 where id=1
select marks,salary,SALARY*12 as anualsal from SPIDERMANN
select * from  batman name order by name 
select * from  batman name,city order by name desc
select * from SPIDERMANN where salary!=25000
select * from SPIDERMANN where salary=25000 and marks=230
select id from SPIDERMANN where marks<SALARY
select * from SPIDERMANN
select * from batman
use warrior
select name,marks from batman natural join SPIDERMANN 

select distinct CITY from batman

select * from batman where name IS NULL
select * from batman where id IS not  NULL

--stored
create procedure spID
as
 BEGIN
SELECT * FROM BATMAN WHERE id =2 
END
create procedure spIDname
as
 BEGIN
SELECT * FROM BATMAN WHERE id =3 AND name='tiya'
create procedure spIDddd
as
 BEGIN
SELECT * FROM BATMAN WHERE id =4 AND name='tiya'
end

end
spIDname
spID

SELECT id FROM batman
UNION ALL
SELECT id FROM SPIDERMANN
SELECT * FROM BATMAN
SELECT * FROM SPIDERMANN
create table dept (EMPID INT,EMPLOYEENAME VARCHAR(80),DEPID INT,SALARY INT,JOINYR INT)
SELECT * FROM DEPT
INSERT INTO dept VALUES(1001,'JOHN',1,23000,2005)
INSERT INTO dept VALUES(1002,'shon',1,33000,2005)
INSERT INTO dept VALUES(1003,'shan',1,43000,2005)
INSERT INTO dept VALUES(1004,'ram',2,24000,2005)
INSERT INTO dept VALUES(1005,'viru',2,28000,2005)
INSERT INTO dept VALUES(1006,'maku',2,29000,2002)
INSERT INTO dept VALUES(1007,'vedu',3,43000,2005)
INSERT INTO dept VALUES(1008,'tia',3,63000,2005)
INSERT INTO dept VALUES(1009,'raman',3,53000,2005)












