use warrior
---already done
select * from SPIDERMANN
--already done
select * from batman
-- new table
create table so (id int,ename varchar(80),salary int,comm int,deptno int)
select * from so
insert into so values(111,'eaman',344444,400,101)
insert into so values(112,'hena',20000,500,101)
insert into so values(113,'praju',30000,200,102)
insert into so values(114,'emran',39000,100,102)
insert into so values(115,'diya',23000,900,103)
insert into so values(116,'aman',80000,800,103)
update so set salary=34000 where id=111
alter table so add age int
alter table so drop column age
select max(salary)from so
select min (salary) from so
select avg(salary)from so
select count(salary)from so
SELECT * FROM SO WHERE ENAME LIKE'N%'
SELECT * FROM SO WHERE ENAME LIKE'%N%'
SELECT * FROM SO WHERE ENAME LIKE'%N'
SELECT * FROM SO WHERE SALARY BETWEEN 34000 AND 80000
SELECT * FROM SO WHERE SALARY IN(34000,80000)
SELECT * FROM SO WHERE SALARY NOT IN(34000,80000)
SELECT * FROM SO WHERE SALARY !=34000
SELECT * FROM SO WHERE SALARY != 80000
------ERROR
SELECT * FROM SO WHERE SALARY != (34000 , 80000)
SELECT * FROM SO WHERE ENAME IN('DIYA')
SELECT * FROM SO WHERE SALARY>34000
SELECT * FROM SO WHERE SALARY<34000
SELECT * FROM SO WHERE SALARY=34000
SELECT * FROM SO WHERE SALARY>=34000
SELECT * FROM SO WHERE SALARY<=34000
SELECT TOP 2* FROM SO 
---- STORED PROCEDURE
CREATE PROCEDURE spTOP
AS
BEGIN
SELECT * FROM SO WHERE SALARY=34000
END
spTOP
ALTER TABLE SO ADD ID INT
SELECT * FROM SO
SELECT ENAME,COMM FROM SO WHERE SALARY>34000 AND DEPTNO=113
SELECT SALARY,SALARY*12,SALARY*3 FROM SO WHERE ENAME='PRAJU'
SELECT ENAME,SALARY FROM SO WHERE deptno IN(102,103)
SELECT ENAME,SALARY FROM SO WHERE deptno NOT IN(102,103)
---ERROR
SELECT ENAME,SALARY FROM SO WHERE deptno != (102,103)
SELECT ENAME,SALARY FROM SO WHERE COMM>200 AND SALARY NOT IN (20000,34000)
SELECT ENAME,SALARY FROM SO WHERE COMM IS NOT NULL



UPDATE SO SET ID =2 WHERE ID=112
UPDATE SO SET ID =3 WHERE ID=113
UPDATE SO SET ID =4 WHERE ID=114
UPDATE SO SET ID =5 WHERE ID=115
UPDATE SO SET ID =6 WHERE ID=116
---JOINS
SELECT SO.ID,ENAME,NAME FROM SO INNER JOIN batman ON SO.ID= BATMAN.ID
SELECT SO.ID,ENAME,NAME FROM SO RIGHT OUTER JOIN batman ON SO.ID= BATMAN.ID
SELECT BATMAN.ID,ENAME,NAME FROM SO LEFT OUTER JOIN batman ON SO.ID= BATMAN.ID
SELECT SO.ID,ENAME,NAME FROM SO FULL JOIN batman ON SO.ID= BATMAN.ID

SELECT ENAME FROM SO
SELECT ENAME,SALARY,SALARY*12 FROM SO
SELECT ENAME,SALARY,SALARY*1,SALARY+1000 FROM SO
SELECT ENAME,SALARY,SALARY*1,SALARY*6+1000 FROM SO
SELECT DISTINCT (SALARY )FROM SO
SELECT ENAME,SALARY,SALARY*12 FROM SO WHERE ename='HENA'
SELECT ENAME FROM SO  WHERE SALARY BETWEEN 23000 AND 39000
SELECT * FROM SO
SELECT MAX(SALARY),MIN (SALARY) FROM SO
use warrior
select min (salary),max(salary) from so group by deptno
SELECT * FROM SO
select min (salary),max(salary) from  so where deptno in(101,102)group by deptno
select salary from so group by salary having count(salary)>1























