--CREATE--
CREATE DATABASE BANK
USE BANK
CREATE TABLE EMPLOYEE(ID INT PRIMARY KEY,NAMES VARCHAR)
SELECT * FROM EMPLOYEE
-- SHOW COLUMNS FROM EMPLOYEE
--INSERT 
INSERT INTO EMPLOYEE VALUES(1,'AMAN','34','PUNE','INDIA')

